# List of constants

# Layer name
LAYER_NAME_BACKGROUND = "background"
LAYER_NAME_DEFAULT = "default"
LAYER_NAME_PLAYER = "player"
LAYER_NAME_FOREGROUND = "foreground"
LAYER_NAME_GUI = "gui"

# Layer level
LAYER_LEVEL_BACKGROUND = 0
LAYER_LEVEL_DEFAULT = 10
LAYER_LEVEL_PLAYER = 11
LAYER_LEVEL_FOREGROUND = 20
LAYER_LEVEL_GUI = 100

# Controller
CONTROLLER_UP = "z"
CONTROLLER_DOWN = "s"
CONTROLLER_LEFT = "q"
CONTROLLER_RIGHT = "d"

CONTROLLER_DELTA = 10

# Player default attributes values
PLAYER_DEFAULT_LIFE = 3

# GUI
GUI_LIFE_COLOR = "red"
